import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
    weight: "400",
    variable: "--font-family-zen",
});

export const metadata: Metadata = {
    title: "kana-shuffle",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${zenKakuGothicNew.variable} antialiased`}>{children}</body>
        </html>
    );
}
